name: basic
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  english_words: ^3.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/appimages/

dev_dependencies:
  flutter_test:
    sdk: flutter
